/**
 * "Situações" — a curated phrasebook of genuinely common, real-life English,
 * grouped by everyday scenario. Powers the Frases page: listen, practise saying
 * each line, shadow the mini-dialogues, and export a scenario straight to Anki.
 *
 * Portuguese is Brazilian (pt-BR). Phrases are kept natural and high-frequency —
 * the stuff you actually say, not textbook sentences. `en` holds the
 * target-language phrase (English or Spanish); `pt` is always the translation.
 */
import type { TargetLang } from '../config'

export interface Phrase {
  en: string
  pt: string
  /** Optional phonetic pronunciation guide (Portuguese-style phonetics), e.g. "dís is mai béig". */
  pronuncia?: string
}
export interface DialogLine {
  who: 'you' | 'them'
  en: string
  pt: string
}
export interface Scenario {
  id: string
  emoji: string
  title: string
  blurb: string
  phrases: Phrase[]
  /** An optional realistic exchange to listen to and shadow line by line. */
  dialog?: DialogLine[]
}

const EN: Scenario[] = [
  {
    id: 'cafe',
    emoji: '☕',
    title: 'Café & Starbucks',
    blurb: 'Pedir seu café como um local — da próxima vez na Holanda. 😄',
    phrases: [
      { en: "Can I get a tall latte, please?", pt: 'Pode ser um latte pequeno (tall), por favor?' },
      { en: "I'd like a medium cappuccino.", pt: 'Eu queria um cappuccino médio.' },
      { en: 'Could I have it with oat milk?', pt: 'Poderia ser com leite de aveia?' },
      { en: 'Decaf, please.', pt: 'Sem cafeína, por favor.' },
      { en: 'Can I get an extra shot of espresso?', pt: 'Pode colocar uma dose extra de espresso?' },
      { en: 'Not too hot, please.', pt: 'Não muito quente, por favor.' },
      { en: 'For here, please. / To go, please.', pt: 'Para comer aqui. / Para viagem.' },
      { en: "What do you recommend?", pt: 'O que você recomenda?' },
      { en: 'Can I pay by card?', pt: 'Posso pagar no cartão?' },
      { en: 'Keep the change.', pt: 'Pode ficar com o troco.' },
    ],
    dialog: [
      { who: 'them', en: 'Hi! What can I get for you?', pt: 'Oi! O que você vai querer?' },
      { who: 'you', en: 'Can I get a tall latte, please?', pt: 'Pode ser um latte pequeno, por favor?' },
      { who: 'them', en: "Sure. What's the name for the order?", pt: 'Claro. Qual o nome do pedido?' },
      { who: 'you', en: "It's Maria.", pt: 'É Maria.' },
      { who: 'them', en: 'For here or to go?', pt: 'Para comer aqui ou para viagem?' },
      { who: 'you', en: 'To go, please.', pt: 'Para viagem, por favor.' },
      { who: 'them', en: 'Anything else?', pt: 'Mais alguma coisa?' },
      { who: 'you', en: "No, that's all. How much is it?", pt: 'Não, é só isso. Quanto fica?' },
      { who: 'them', en: "That'll be five forty.", pt: 'Dá cinco e quarenta.' },
      { who: 'you', en: 'Here you go. Thank you!', pt: 'Aqui está. Obrigada!' },
    ],
  },
  {
    id: 'greetings',
    emoji: '👋',
    title: 'Cumprimentos & papo',
    blurb: 'Quebrar o gelo e manter uma conversa leve.',
    phrases: [
      { en: 'Hi, how are you doing?', pt: 'Oi, como você está?' },
      { en: "I'm good, thanks. And you?", pt: 'Estou bem, obrigada. E você?' },
      { en: 'Nice to meet you.', pt: 'Prazer em conhecer você.' },
      { en: 'What do you do?', pt: 'O que você faz (de trabalho)?' },
      { en: 'Where are you from?', pt: 'De onde você é?' },
      { en: 'How was your weekend?', pt: 'Como foi seu fim de semana?' },
      { en: 'Sorry, could you say that again?', pt: 'Desculpa, pode repetir?' },
      { en: 'It was great talking to you.', pt: 'Foi ótimo falar com você.' },
      { en: 'Take care! See you soon.', pt: 'Se cuida! Até logo.' },
    ],
    dialog: [
      { who: 'them', en: 'Hey! Good to see you. How are you doing?', pt: 'Ei! Que bom te ver. Como você está?' },
      { who: 'you', en: "I'm doing really well, thanks! How about you?", pt: 'Estou muito bem, obrigada! E você?' },
      { who: 'them', en: "Pretty good! Have you been up to anything fun lately?", pt: 'Bem também! Tem feito algo divertido ultimamente?' },
      { who: 'you', en: 'Just got back from a trip. It was amazing.', pt: 'Acabei de voltar de uma viagem. Foi incrível.' },
      { who: 'them', en: 'Oh, nice! Where did you go?', pt: 'Que legal! Onde você foi?' },
      { who: 'you', en: 'Amsterdam. Have you ever been?', pt: 'Amsterdã. Você já foi?' },
      { who: 'them', en: 'Not yet, but I would love to. What do you do, by the way?', pt: 'Ainda não, mas adoraria. O que você faz, aliás?' },
      { who: 'you', en: "I'm a teacher. Where are you from?", pt: 'Sou professora. De onde você é?' },
      { who: 'them', en: "I'm from London. It was great talking to you!", pt: 'Sou de Londres. Foi ótimo falar com você!' },
      { who: 'you', en: 'You too! Take care. See you soon!', pt: 'Igualmente! Se cuida. Até logo!' },
    ],
  },
  {
    id: 'restaurant',
    emoji: '🍽️',
    title: 'Restaurante',
    blurb: 'Da mesa à conta, sem travar.',
    phrases: [
      { en: 'A table for two, please.', pt: 'Uma mesa para dois, por favor.' },
      { en: 'Could we see the menu?', pt: 'Podemos ver o cardápio?' },
      { en: "What's the dish of the day?", pt: 'Qual é o prato do dia?' },
      { en: "I'll have the chicken, please.", pt: 'Vou querer o frango, por favor.' },
      { en: "I'm allergic to nuts.", pt: 'Eu sou alérgica a castanhas/nozes.' },
      { en: 'Can I have some water, please?', pt: 'Pode trazer água, por favor?' },
      { en: 'This is delicious!', pt: 'Está delicioso!' },
      { en: 'Could we get the check, please?', pt: 'Pode trazer a conta, por favor?' },
      { en: 'Can we split the bill?', pt: 'Dá para dividir a conta?' },
    ],
    dialog: [
      { who: 'them', en: 'Good evening! Do you have a reservation?', pt: 'Boa noite! Vocês têm reserva?' },
      { who: 'you', en: "No, we don't. Is there a table for two available?", pt: 'Não. Tem mesa para dois disponível?' },
      { who: 'them', en: 'Of course, right this way. Here is your menu.', pt: 'Claro, por aqui. Aqui está o cardápio.' },
      { who: 'you', en: "Thank you. What's the dish of the day?", pt: 'Obrigada. Qual é o prato do dia?' },
      { who: 'them', en: 'Today we have grilled salmon with roasted vegetables.', pt: 'Hoje temos salmão grelhado com legumes assados.' },
      { who: 'you', en: "That sounds great. I'll have that, please.", pt: 'Parece ótimo. Vou querer isso, por favor.' },
      { who: 'them', en: 'Excellent choice. And to drink?', pt: 'Ótima escolha. E para beber?' },
      { who: 'you', en: 'Just water, please. Could we get the check when you are ready?', pt: 'Só água, por favor. Pode trazer a conta quando puder?' },
      { who: 'them', en: 'Of course. I will bring it right over.', pt: 'Claro. Já trago.' },
    ],
  },
  {
    id: 'shopping',
    emoji: '🛍️',
    title: 'Compras',
    blurb: 'Provar, escolher e pagar.',
    phrases: [
      { en: "I'm just looking, thanks.", pt: 'Só estou dando uma olhada, obrigada.' },
      { en: 'How much is this?', pt: 'Quanto custa isto?' },
      { en: 'Do you have this in a smaller size?', pt: 'Você tem isto num tamanho menor?' },
      { en: 'Can I try it on?', pt: 'Posso experimentar?' },
      { en: 'Where are the fitting rooms?', pt: 'Onde ficam os provadores?' },
      { en: "I'll take it.", pt: 'Vou levar.' },
      { en: 'Do you accept cards?', pt: 'Vocês aceitam cartão?' },
      { en: 'Can I get a receipt, please?', pt: 'Pode me dar o recibo, por favor?' },
    ],
    dialog: [
      { who: 'them', en: 'Hi there! Can I help you find anything?', pt: 'Oi! Posso te ajudar a encontrar algo?' },
      { who: 'you', en: "I'm just looking, thanks. Actually, do you have this jacket in a smaller size?", pt: 'Só estou dando uma olhada, obrigada. Na verdade, você tem essa jaqueta num tamanho menor?' },
      { who: 'them', en: 'Let me check. What size are you looking for?', pt: 'Deixa eu verificar. Qual tamanho você está procurando?' },
      { who: 'you', en: 'A small, if you have it.', pt: 'P, se tiver.' },
      { who: 'them', en: 'Yes, we have one left. Would you like to try it on?', pt: 'Sim, temos um. Quer experimentar?' },
      { who: 'you', en: 'Yes please. Where are the fitting rooms?', pt: 'Sim, por favor. Onde ficam os provadores?' },
      { who: 'them', en: 'Just around the corner on your right.', pt: 'Logo ali na esquina à sua direita.' },
      { who: 'you', en: "Perfect. I'll take it! Do you accept cards?", pt: 'Perfeito. Vou levar! Vocês aceitam cartão?' },
      { who: 'them', en: 'Yes, all major cards. Can I get you a receipt?', pt: 'Sim, todos os cartões. Quer um recibo?' },
    ],
  },
  {
    id: 'directions',
    emoji: '🧭',
    title: 'Direções & transporte',
    blurb: 'Se achar na cidade e se virar no transporte.',
    phrases: [
      { en: 'Excuse me, how do I get to the station?', pt: 'Com licença, como chego à estação?' },
      { en: 'Is it far from here?', pt: 'É longe daqui?' },
      { en: 'Is this the right way to the museum?', pt: 'É por aqui o caminho para o museu?' },
      { en: 'Which platform is it?', pt: 'Qual é a plataforma?' },
      { en: 'A ticket to the city center, please.', pt: 'Uma passagem para o centro, por favor.' },
      { en: 'Does this bus go downtown?', pt: 'Este ônibus vai para o centro?' },
      { en: 'Could you tell me when to get off?', pt: 'Pode me avisar onde descer?' },
      { en: "I think I'm lost.", pt: 'Acho que me perdi.' },
    ],
    dialog: [
      { who: 'you', en: 'Excuse me, how do I get to the central station?', pt: 'Com licença, como chego à estação central?' },
      { who: 'them', en: 'Sure! Go straight ahead and turn left at the traffic lights.', pt: 'Claro! Siga em frente e vire à esquerda no semáforo.' },
      { who: 'you', en: 'Is it far from here?', pt: 'É longe daqui?' },
      { who: 'them', en: 'About a ten-minute walk. You cannot miss it.', pt: 'Uns dez minutos a pé. Não tem como errar.' },
      { who: 'you', en: 'And does this bus go downtown?', pt: 'E esse ônibus vai para o centro?' },
      { who: 'them', en: 'Yes, the number 12 goes all the way to the city center.', pt: 'Sim, o número 12 vai até o centro da cidade.' },
      { who: 'you', en: 'Could you tell me when to get off?', pt: 'Pode me avisar onde descer?' },
      { who: 'them', en: 'Of course. The stop is called Central Square.', pt: 'Claro. A parada se chama Praça Central.' },
      { who: 'you', en: 'Thank you so much. You have been really helpful.', pt: 'Muito obrigada. Você foi muito prestativo.' },
    ],
  },
  {
    id: 'travel',
    emoji: '✈️',
    title: 'Aeroporto & hotel',
    blurb: 'Check-in, embarque e hospedagem.',
    phrases: [
      { en: "I'd like to check in, please.", pt: 'Eu gostaria de fazer o check-in, por favor.' },
      { en: 'Here is my passport.', pt: 'Aqui está meu passaporte.' },
      { en: 'Just one carry-on.', pt: 'Só uma bagagem de mão.' },
      { en: 'Which gate is my flight?', pt: 'Qual é o portão do meu voo?' },
      { en: 'I have a reservation under Maria.', pt: 'Tenho uma reserva no nome de Maria.' },
      { en: 'What time is check-out?', pt: 'Que horas é o check-out?' },
      { en: 'Is breakfast included?', pt: 'O café da manhã está incluído?' },
      { en: 'Could I have the Wi-Fi password?', pt: 'Pode me passar a senha do Wi-Fi?' },
    ],
    dialog: [
      { who: 'them', en: 'Good morning! Can I see your passport, please?', pt: 'Bom dia! Posso ver seu passaporte, por favor?' },
      { who: 'you', en: 'Of course. Here you go. I would like to check in.', pt: 'Claro. Aqui está. Gostaria de fazer o check-in.' },
      { who: 'them', en: 'Are you checking any bags today?', pt: 'Vai despachar alguma bagagem hoje?' },
      { who: 'you', en: 'Just one carry-on. No checked bags.', pt: 'Só uma bagagem de mão. Sem bagagem despachada.' },
      { who: 'them', en: 'Great. Your gate is B12. Boarding starts at two thirty.', pt: 'Ótimo. Seu portão é o B12. Embarque começa às duas e meia.' },
      { who: 'you', en: 'Thank you. I also have a reservation at the hotel. Is breakfast included?', pt: 'Obrigada. Tenho também uma reserva no hotel. O café da manhã está incluído?' },
      { who: 'them', en: 'Yes, breakfast is served from seven to ten in the dining room.', pt: 'Sim, o café da manhã é servido das sete às dez na sala de jantar.' },
      { who: 'you', en: 'Perfect. Could I have the Wi-Fi password?', pt: 'Perfeito. Pode me passar a senha do Wi-Fi?' },
      { who: 'them', en: 'It is on the welcome card in your room. Have a great stay!', pt: 'Está no cartão de boas-vindas no seu quarto. Boa estadia!' },
    ],
  },
  {
    id: 'help',
    emoji: '🆘',
    title: 'Ajuda & imprevistos',
    blurb: 'Para quando algo sai do plano.',
    phrases: [
      { en: 'Can you help me, please?', pt: 'Você pode me ajudar, por favor?' },
      { en: "I don't understand.", pt: 'Eu não entendi.' },
      { en: 'Could you speak more slowly?', pt: 'Você pode falar mais devagar?' },
      { en: 'How do you say this in English?', pt: 'Como se diz isto em inglês?' },
      { en: "I've lost my phone.", pt: 'Eu perdi meu celular.' },
      { en: 'Where is the nearest pharmacy?', pt: 'Onde fica a farmácia mais próxima?' },
      { en: "I'm not feeling well.", pt: 'Não estou me sentindo bem.' },
      { en: 'Thank you so much for your help.', pt: 'Muito obrigada pela ajuda.' },
    ],
    dialog: [
      { who: 'you', en: 'Excuse me, can you help me, please?', pt: 'Com licença, você pode me ajudar, por favor?' },
      { who: 'them', en: 'Of course! What is wrong?', pt: 'Claro! O que aconteceu?' },
      { who: 'you', en: "I think I have lost my phone somewhere around here.", pt: 'Acho que perdi meu celular em algum lugar aqui por perto.' },
      { who: 'them', en: 'Oh no. Did you check at the information desk?', pt: 'Que pena. Você verificou na mesa de informações?' },
      { who: 'you', en: 'Not yet. Where is it?', pt: 'Ainda não. Onde fica?' },
      { who: 'them', en: 'It is on the ground floor, near the main entrance.', pt: 'Fica no térreo, perto da entrada principal.' },
      { who: 'you', en: 'Thank you. Also, I am not feeling well. Where is the nearest pharmacy?', pt: 'Obrigada. Também não estou me sentindo bem. Onde fica a farmácia mais próxima?' },
      { who: 'them', en: 'There is one just outside, turn left and it is on the corner.', pt: 'Tem uma logo aqui fora, vire à esquerda e fica na esquina.' },
      { who: 'you', en: 'Thank you so much for your help.', pt: 'Muito obrigada pela sua ajuda.' },
    ],
  },
  {
    id: 'doctor',
    emoji: '🏥',
    title: 'Médico & farmácia',
    blurb: 'Explicar sintomas e entender o que o médico diz.',
    phrases: [
      { en: "I'm not feeling well.", pt: 'Não estou me sentindo bem.' },
      { en: 'I have a headache and a sore throat.', pt: 'Estou com dor de cabeça e garganta inflamada.' },
      { en: "I've had a fever since yesterday.", pt: 'Estou com febre desde ontem.' },
      { en: "I'm allergic to penicillin.", pt: 'Sou alérgica à penicilina.' },
      { en: 'How often should I take this?', pt: 'Com que frequência devo tomar isso?' },
      { en: 'Take one tablet three times a day with food.', pt: 'Tome um comprimido três vezes ao dia com comida.' },
      { en: 'Do I need a prescription for this?', pt: 'Preciso de receita para isso?' },
      { en: 'Is there a pharmacy nearby?', pt: 'Tem alguma farmácia por perto?' },
      { en: "I'd like to make an appointment.", pt: 'Gostaria de marcar uma consulta.' },
    ],
    dialog: [
      { who: 'them', en: 'Hello, come in. What brings you in today?', pt: 'Olá, pode entrar. O que te traz aqui hoje?' },
      { who: 'you', en: "I'm not feeling well. I have a sore throat and a headache.", pt: 'Não estou me sentindo bem. Estou com garganta inflamada e dor de cabeça.' },
      { who: 'them', en: 'How long have you had these symptoms?', pt: 'Há quanto tempo você está com esses sintomas?' },
      { who: 'you', en: 'Since yesterday morning. I also have a slight fever.', pt: 'Desde ontem de manhã. Também estou com febre baixa.' },
      { who: 'them', en: 'Do you have any allergies to medication?', pt: 'Você tem alguma alergia a medicamentos?' },
      { who: 'you', en: "Yes, I'm allergic to penicillin.", pt: 'Sim, sou alérgica à penicilina.' },
      { who: 'them', en: 'Okay. I will prescribe something safe for you. Take one tablet three times a day with food.', pt: 'Ok. Vou te receitar algo seguro. Tome um comprimido três vezes ao dia com comida.' },
      { who: 'you', en: 'How many days should I take it?', pt: 'Por quantos dias devo tomar?' },
      { who: 'them', en: 'For five days. Come back if you do not feel better in two days.', pt: 'Por cinco dias. Volte se não melhorar em dois dias.' },
      { who: 'you', en: 'Thank you, doctor. Is there a pharmacy nearby?', pt: 'Obrigada, doutor. Tem alguma farmácia por perto?' },
    ],
  },
  {
    id: 'dia-a-dia',
    emoji: '🗓️',
    title: 'Frases do dia a dia',
    blurb: 'Frases simples e frequentes para praticar todo santo dia.',
    phrases: [
      { en: 'This is my bag.', pt: 'Esta é minha bolsa.', pronuncia: 'dís is mai béig' },
      { en: 'This is my coffee.', pt: 'Este é meu café.', pronuncia: 'dís is mai cófi' },
      { en: 'These are my friends.', pt: 'Estes são meus amigos.', pronuncia: 'díiz ar mai frênds' },
      { en: 'That is a nice house.', pt: 'Aquela é uma casa bonita.', pronuncia: 'dét is a náis háus' },
      { en: 'That is a big house.', pt: 'Aquela é uma casa grande.', pronuncia: 'dét is a big háus' },
      { en: "It's cold today.", pt: 'Está frio hoje.', pronuncia: 'íts côuld tudêi' },
      { en: "It's mine.", pt: 'É meu.', pronuncia: 'íts máin' },
      { en: 'There is a café.', pt: 'Tem um café.', pronuncia: 'dér is a kafêi' },
      { en: 'There is a market.', pt: 'Tem um mercado.', pronuncia: 'dér is a márket' },
      { en: 'There are two markets.', pt: 'Tem dois mercados.', pronuncia: 'dér ar tu márkets' },
      { en: 'Where is the bathroom?', pt: 'Onde fica o banheiro?', pronuncia: 'uér is dâ bá-thrum' },
      { en: 'Where is my phone?', pt: 'Onde está meu celular?', pronuncia: 'uér is mai fôun' },
      { en: 'My phone is on the table.', pt: 'Meu celular está em cima da mesa.', pronuncia: 'mai fôun is ón dâ têibol' },
      { en: 'My coffee is on the table.', pt: 'Meu café está em cima da mesa.', pronuncia: 'mai cófi is ón dâ têibol' },
      { en: "I'm at home.", pt: 'Estou em casa.', pronuncia: 'aim ét hôum' },
      { en: 'A cup of coffee.', pt: 'Uma xícara de café.', pronuncia: 'a câp óv cófi' },
      { en: 'Do you want coffee or tea?', pt: 'Você quer café ou chá?', pronuncia: 'du iú uónt cófi ór tí' },
      { en: 'I like coffee. I also like tea.', pt: 'Gosto de café. Também gosto de chá.', pronuncia: 'ai láik cófi. ai ólsou láik tí' },
      { en: 'Everything is ready.', pt: 'Tudo está pronto.', pronuncia: 'évri-thin is rédi' },
      { en: 'Everyone is here.', pt: 'Todo mundo está aqui.', pronuncia: 'évri-uan is rír' },
      { en: 'Your bag is nice.', pt: 'Sua bolsa é bonita.', pronuncia: 'iór béig is náis' },
      { en: "We're at home.", pt: 'Estamos em casa.', pronuncia: 'uír ét hôum' },
      { en: "I'll call you later.", pt: 'Eu te ligo mais tarde.', pronuncia: 'áil cól iú lêiter' },
      { en: "I've got a phone.", pt: 'Eu tenho um celular.', pronuncia: 'áiv gót a fôun' },
      { en: "I can't talk now.", pt: 'Não consigo falar agora.', pronuncia: 'ai quént tók náu' },
      { en: 'Tell me.', pt: 'Me conta.', pronuncia: 'tél mí' },
      { en: 'Give me water.', pt: 'Me dá água.', pronuncia: 'guiv mí uóter' },
      { en: 'Keep it.', pt: 'Fica com isso.', pronuncia: 'kíip ít' },
      { en: 'When are you home?', pt: 'Quando você está em casa?', pronuncia: 'uén ar iú hôum' },
      { en: 'I get coffee every day.', pt: 'Eu pego café todo dia.', pronuncia: 'ai guét cófi évri dêi' },
      { en: "I'm getting tired.", pt: 'Estou ficando cansada.', pronuncia: 'aim guétin táierd' },
      { en: 'I have to go.', pt: 'Tenho que ir.', pronuncia: 'ai hév tu gôu' },
      { en: 'I gotta go.', pt: 'Tenho que ir. (informal, só falado)', pronuncia: 'ai gótâ gôu' },
      { en: 'The coffee is gone.', pt: 'O café acabou.', pronuncia: 'dâ cófi is gón' },
      { en: 'Another coffee, please.', pt: 'Mais um café, por favor.', pronuncia: 'anâdâr cófi plíiz' },
      { en: "It's cold, though.", pt: 'Está frio, porém...', pronuncia: 'íts côuld dôu' },
      { en: 'I thought it was ready.', pt: 'Pensei que estava pronto.', pronuncia: 'ai thót it uós rédi' },
      { en: 'Hi! Where are you?', pt: 'Oi! Onde você está?', pronuncia: 'rai! uér ar iú' },
      { en: 'When can you call me?', pt: 'Quando você pode me ligar?', pronuncia: 'uén quen iú cól mí' },
      { en: 'Tell me everything!', pt: 'Me conta tudo!', pronuncia: 'tél mí évri-thin' },
      { en: "I'm at home and I'm going to have lunch.", pt: 'Estou em casa e vou almoçar.', pronuncia: 'aim ét hôum end aim gôuin tu hév lânch' },
      { en: "Everything went well, but I'm getting tired.", pt: 'Tudo correu bem, mas estou ficando cansada.', pronuncia: 'évri-thin uent uél, bât aim guétin táierd' },
      { en: 'When I speak English, I get very happy!', pt: 'Quando falo inglês, eu fico muito feliz!', pronuncia: 'uén ai spíik ínglich, ai guét véri répi' },
    ],
  },
]

// Castilian Spanish (Spain). `en` holds the Spanish phrase; `pt` the translation.
const ES: Scenario[] = [
  {
    id: 'cafe',
    emoji: '☕',
    title: 'Café & Starbucks',
    blurb: 'Pedir tu café como un local. 😄',
    phrases: [
      { en: 'Un café con leche, por favor.', pt: 'Um café com leite, por favor.' },
      { en: '¿Me pones un cortado?', pt: 'Pode me trazer um cortado (café com pouco leite)?' },
      { en: 'Quería un café solo.', pt: 'Eu queria um café puro (expresso).' },
      { en: '¿Lo tienes con leche de avena?', pt: 'Você tem com leite de aveia?' },
      { en: 'Sin azúcar, por favor.', pt: 'Sem açúcar, por favor.' },
      { en: 'Para tomar aquí. / Para llevar.', pt: 'Para tomar aqui. / Para viagem.' },
      { en: '¿Qué me recomiendas?', pt: 'O que você me recomenda?' },
      { en: '¿Puedo pagar con tarjeta?', pt: 'Posso pagar com cartão?' },
      { en: 'Quédate con el cambio.', pt: 'Pode ficar com o troco.' },
    ],
    dialog: [
      { who: 'them', en: '¡Hola! ¿Qué te pongo?', pt: 'Olá! O que vai querer?' },
      { who: 'you', en: 'Un café con leche, por favor.', pt: 'Um café com leite, por favor.' },
      { who: 'them', en: '¿Para tomar aquí o para llevar?', pt: 'Para tomar aqui ou para viagem?' },
      { who: 'you', en: 'Para llevar, por favor.', pt: 'Para viagem, por favor.' },
      { who: 'them', en: '¿Algo más?', pt: 'Mais alguma coisa?' },
      { who: 'you', en: 'No, eso es todo. ¿Cuánto es?', pt: 'Não, é só isso. Quanto fica?' },
      { who: 'them', en: 'Son dos con cuarenta.', pt: 'Dá dois e quarenta.' },
      { who: 'you', en: 'Aquí tienes. ¡Gracias!', pt: 'Aqui está. Obrigada!' },
    ],
  },
  {
    id: 'greetings',
    emoji: '👋',
    title: 'Saludos & charla',
    blurb: 'Romper o gelo e manter uma conversa leve.',
    phrases: [
      { en: 'Hola, ¿qué tal?', pt: 'Oi, tudo bem?' },
      { en: 'Muy bien, gracias. ¿Y tú?', pt: 'Muito bem, obrigada. E você?' },
      { en: 'Encantada de conocerte.', pt: 'Prazer em conhecer você.' },
      { en: '¿A qué te dedicas?', pt: 'O que você faz (de trabalho)?' },
      { en: '¿De dónde eres?', pt: 'De onde você é?' },
      { en: '¿Qué tal el fin de semana?', pt: 'Como foi o fim de semana?' },
      { en: 'Perdona, ¿puedes repetir?', pt: 'Desculpa, pode repetir?' },
      { en: 'Me ha encantado hablar contigo.', pt: 'Adorei falar com você.' },
      { en: '¡Cuídate! Hasta pronto.', pt: 'Se cuida! Até logo.' },
    ],
    dialog: [
      { who: 'them', en: '¡Hola! Creo que no nos conocemos. Soy Carlos.', pt: 'Oi! Acho que não nos conhecemos. Sou Carlos.' },
      { who: 'you', en: 'Encantada, Carlos. Soy María.', pt: 'Prazer, Carlos. Sou María.' },
      { who: 'them', en: '¿De dónde eres, María?', pt: 'De onde você é, María?' },
      { who: 'you', en: 'Soy de Brasil. ¿Y tú?', pt: 'Sou do Brasil. E você?' },
      { who: 'them', en: 'Soy de Madrid. ¿A qué te dedicas?', pt: 'Sou de Madri. O que você faz?' },
      { who: 'you', en: 'Soy diseñadora. ¿Y tú?', pt: 'Sou designer. E você?' },
      { who: 'them', en: 'Trabajo en tecnología. ¿Cuánto tiempo llevas aquí?', pt: 'Trabalho com tecnologia. Há quanto tempo você está aqui?' },
      { who: 'you', en: 'Solo unos meses. Me ha encantado hablar contigo.', pt: 'Só alguns meses. Adorei falar com você.' },
      { who: 'them', en: '¡Igualmente! ¡Cuídate, hasta pronto!', pt: 'Igualmente! Se cuida, até logo!' },
    ],
  },
  {
    id: 'restaurant',
    emoji: '🍽️',
    title: 'Restaurante',
    blurb: 'Da mesa à conta, sem travar.',
    phrases: [
      { en: 'Una mesa para dos, por favor.', pt: 'Uma mesa para dois, por favor.' },
      { en: '¿Nos trae la carta?', pt: 'Pode trazer o cardápio?' },
      { en: '¿Cuál es el plato del día?', pt: 'Qual é o prato do dia?' },
      { en: 'Para mí el pollo, por favor.', pt: 'Para mim o frango, por favor.' },
      { en: 'Soy alérgica a los frutos secos.', pt: 'Sou alérgica a castanhas/nozes.' },
      { en: '¿Me trae un poco de agua?', pt: 'Pode trazer um pouco de água?' },
      { en: '¡Está buenísimo!', pt: 'Está uma delícia!' },
      { en: 'La cuenta, por favor.', pt: 'A conta, por favor.' },
      { en: '¿Podemos pagar a medias?', pt: 'Dá para dividir a conta?' },
    ],
    dialog: [
      { who: 'them', en: '¡Buenas noches! ¿Tienen reserva?', pt: 'Boa noite! Vocês têm reserva?' },
      { who: 'you', en: 'No, no tenemos. ¿Tienen mesa para dos?', pt: 'Não. Têm mesa para dois?' },
      { who: 'them', en: 'Sí, por aquí. Aquí tienen la carta.', pt: 'Sim, por aqui. Aqui está o cardápio.' },
      { who: 'you', en: 'Gracias. ¿Cuál es el plato del día?', pt: 'Obrigada. Qual é o prato do dia?' },
      { who: 'them', en: 'Hoy tenemos salmón a la plancha con verduras asadas.', pt: 'Hoje temos salmão grelhado com legumes assados.' },
      { who: 'you', en: 'Qué buena pinta. Para mí eso, por favor.', pt: 'Que boa aparência. Para mim isso, por favor.' },
      { who: 'them', en: '¿Y para beber?', pt: 'E para beber?' },
      { who: 'you', en: 'Solo agua, gracias. ¿Nos puede traer la cuenta cuando pueda?', pt: 'Só água, obrigada. Pode trazer a conta quando puder?' },
      { who: 'them', en: 'Por supuesto. Ahora mismo se la traigo.', pt: 'Claro. Já trago.' },
    ],
  },
  {
    id: 'shopping',
    emoji: '🛍️',
    title: 'Compras',
    blurb: 'Provar, escolher e pagar.',
    phrases: [
      { en: 'Solo estoy mirando, gracias.', pt: 'Só estou dando uma olhada, obrigada.' },
      { en: '¿Cuánto cuesta esto?', pt: 'Quanto custa isto?' },
      { en: '¿Lo tienes en una talla más pequeña?', pt: 'Você tem num tamanho menor?' },
      { en: '¿Me lo puedo probar?', pt: 'Posso experimentar?' },
      { en: '¿Dónde están los probadores?', pt: 'Onde ficam os provadores?' },
      { en: 'Me lo llevo.', pt: 'Vou levar.' },
      { en: '¿Aceptan tarjeta?', pt: 'Vocês aceitam cartão?' },
      { en: '¿Me da el recibo, por favor?', pt: 'Pode me dar o recibo, por favor?' },
    ],
    dialog: [
      { who: 'them', en: '¡Hola! ¿Le puedo ayudar en algo?', pt: 'Oi! Posso te ajudar em algo?' },
      { who: 'you', en: 'Solo estoy mirando, gracias. Aunque... ¿tiene esta chaqueta en una talla más pequeña?', pt: 'Só estou dando uma olhada. Mas... tem essa jaqueta num tamanho menor?' },
      { who: 'them', en: 'Déjeme mirar en el almacén. ¿Qué talla busca?', pt: 'Deixa eu verificar no estoque. Qual tamanho você procura?' },
      { who: 'you', en: 'Una talla pequeña, si tiene.', pt: 'Tamanho P, se tiver.' },
      { who: 'them', en: 'Sí, nos queda una. ¿Quiere probársela?', pt: 'Sim, temos uma. Quer experimentar?' },
      { who: 'you', en: 'Sí, por favor. ¿Dónde están los probadores?', pt: 'Sim, por favor. Onde ficam os provadores?' },
      { who: 'them', en: 'Al fondo a la derecha.', pt: 'Ao fundo à direita.' },
      { who: 'you', en: 'Perfecto. Me lo llevo. ¿Aceptan tarjeta?', pt: 'Perfeito. Vou levar. Vocês aceitam cartão?' },
      { who: 'them', en: 'Sí, todas las tarjetas. ¿Le doy el recibo?', pt: 'Sim, todos os cartões. Quer o recibo?' },
    ],
  },
  {
    id: 'directions',
    emoji: '🧭',
    title: 'Direcciones & transporte',
    blurb: 'Se achar na cidade e se virar no transporte.',
    phrases: [
      { en: 'Perdona, ¿cómo llego a la estación?', pt: 'Com licença, como chego à estação?' },
      { en: '¿Está lejos de aquí?', pt: 'É longe daqui?' },
      { en: '¿Es este el camino al museo?', pt: 'É por aqui o caminho para o museu?' },
      { en: '¿Qué andén es?', pt: 'Qual é a plataforma?' },
      { en: 'Un billete para el centro, por favor.', pt: 'Uma passagem para o centro, por favor.' },
      { en: '¿Este autobús va al centro?', pt: 'Este ônibus vai para o centro?' },
      { en: '¿Me avisa cuándo bajar?', pt: 'Pode me avisar onde descer?' },
      { en: 'Creo que me he perdido.', pt: 'Acho que me perdi.' },
    ],
    dialog: [
      { who: 'you', en: 'Perdona, ¿cómo llego a la estación central?', pt: 'Com licença, como chego à estação central?' },
      { who: 'them', en: 'Claro. Sigue todo recto y gira a la izquierda en el semáforo.', pt: 'Claro. Siga em frente e vire à esquerda no semáforo.' },
      { who: 'you', en: '¿Está lejos de aquí?', pt: 'É longe daqui?' },
      { who: 'them', en: 'Unos diez minutos andando. No tiene pérdida.', pt: 'Uns dez minutos a pé. Não tem como errar.' },
      { who: 'you', en: '¿Y este autobús va al centro?', pt: 'E esse ônibus vai para o centro?' },
      { who: 'them', en: 'Sí, el número 12 va hasta el centro de la ciudad.', pt: 'Sim, o número 12 vai até o centro da cidade.' },
      { who: 'you', en: '¿Me avisa cuándo tengo que bajar?', pt: 'Pode me avisar quando preciso descer?' },
      { who: 'them', en: 'Por supuesto. La parada se llama Plaza Central.', pt: 'Claro. A parada se chama Praça Central.' },
      { who: 'you', en: 'Muchísimas gracias. Ha sido muy amable.', pt: 'Muito obrigada. Você foi muito gentil.' },
    ],
  },
  {
    id: 'travel',
    emoji: '✈️',
    title: 'Aeropuerto & hotel',
    blurb: 'Check-in, embarque e hospedagem.',
    phrases: [
      { en: 'Quería facturar, por favor.', pt: 'Eu queria fazer o check-in (da bagagem), por favor.' },
      { en: 'Aquí tiene mi pasaporte.', pt: 'Aqui está meu passaporte.' },
      { en: 'Solo llevo equipaje de mano.', pt: 'Só levo bagagem de mão.' },
      { en: '¿De qué puerta sale mi vuelo?', pt: 'De qual portão sai meu voo?' },
      { en: 'Tengo una reserva a nombre de María.', pt: 'Tenho uma reserva no nome de María.' },
      { en: '¿A qué hora es la salida?', pt: 'Que horas é o check-out?' },
      { en: '¿El desayuno está incluido?', pt: 'O café da manhã está incluído?' },
      { en: '¿Me da la contraseña del wifi?', pt: 'Pode me passar a senha do Wi-Fi?' },
    ],
    dialog: [
      { who: 'them', en: '¡Buenos días! ¿Su pasaporte, por favor?', pt: 'Bom dia! Seu passaporte, por favor?' },
      { who: 'you', en: 'Aquí tiene. Quería facturar, por favor.', pt: 'Aqui está. Eu queria fazer o check-in, por favor.' },
      { who: 'them', en: '¿Lleva equipaje para facturar?', pt: 'Vai despachar alguma bagagem?' },
      { who: 'you', en: 'Solo equipaje de mano, sin maletas.', pt: 'Só bagagem de mão, sem malas.' },
      { who: 'them', en: 'Perfecto. Su puerta de embarque es la B12. Sale a las dos y media.', pt: 'Perfeito. Seu portão é o B12. Sai às duas e meia.' },
      { who: 'you', en: 'Gracias. ¿El desayuno está incluido en el hotel?', pt: 'Obrigada. O café da manhã está incluído no hotel?' },
      { who: 'them', en: 'Sí, se sirve de siete a diez en el comedor.', pt: 'Sim, é servido das sete às dez no refeitório.' },
      { who: 'you', en: '¿Me puede dar la contraseña del wifi?', pt: 'Pode me passar a senha do Wi-Fi?' },
      { who: 'them', en: 'Está en la tarjeta de bienvenida de su habitación. ¡Que tenga buen vuelo!', pt: 'Está no cartão de boas-vindas no seu quarto. Bom voo!' },
    ],
  },
  {
    id: 'help',
    emoji: '🆘',
    title: 'Ayuda & imprevistos',
    blurb: 'Para quando algo sai do plano.',
    phrases: [
      { en: '¿Me puedes ayudar, por favor?', pt: 'Você pode me ajudar, por favor?' },
      { en: 'No entiendo.', pt: 'Eu não entendi.' },
      { en: '¿Puedes hablar más despacio?', pt: 'Você pode falar mais devagar?' },
      { en: '¿Cómo se dice esto en español?', pt: 'Como se diz isto em espanhol?' },
      { en: 'He perdido el móvil.', pt: 'Eu perdi o celular.' },
      { en: '¿Dónde está la farmacia más cercana?', pt: 'Onde fica a farmácia mais próxima?' },
      { en: 'No me encuentro bien.', pt: 'Não estou me sentindo bem.' },
      { en: 'Muchas gracias por tu ayuda.', pt: 'Muito obrigada pela ajuda.' },
    ],
    dialog: [
      { who: 'you', en: 'Perdona, ¿me puedes ayudar, por favor?', pt: 'Com licença, você pode me ajudar, por favor?' },
      { who: 'them', en: '¡Claro! ¿Qué te pasa?', pt: 'Claro! O que aconteceu?' },
      { who: 'you', en: 'Creo que he perdido el móvil por aquí.', pt: 'Acho que perdi o celular aqui por perto.' },
      { who: 'them', en: '¿Has preguntado en objetos perdidos?', pt: 'Você perguntou em achados e perdidos?' },
      { who: 'you', en: 'Todavía no. ¿Dónde está?', pt: 'Ainda não. Onde fica?' },
      { who: 'them', en: 'Está en la planta baja, cerca de la entrada principal.', pt: 'Fica no térreo, perto da entrada principal.' },
      { who: 'you', en: 'Gracias. Además, no me encuentro bien. ¿Hay una farmacia cerca?', pt: 'Obrigada. Além disso, não estou me sentindo bem. Tem farmácia perto?' },
      { who: 'them', en: 'Sí, hay una justo a la salida, a la izquierda en la esquina.', pt: 'Sim, tem uma logo na saída, à esquerda na esquina.' },
      { who: 'you', en: 'Muchas gracias por tu ayuda.', pt: 'Muito obrigada pela sua ajuda.' },
    ],
  },
  {
    id: 'doctor',
    emoji: '🏥',
    title: 'Médico & farmacia',
    blurb: 'Explicar síntomas y entender al médico.',
    phrases: [
      { en: 'No me encuentro bien.', pt: 'Não estou me sentindo bem.' },
      { en: 'Me duele la cabeza y tengo la garganta irritada.', pt: 'Estou com dor de cabeça e garganta inflamada.' },
      { en: 'Llevo fiebre desde ayer.', pt: 'Estou com febre desde ontem.' },
      { en: 'Soy alérgica a la penicilina.', pt: 'Sou alérgica à penicilina.' },
      { en: '¿Cada cuánto tengo que tomarlo?', pt: 'Com que frequência devo tomar isso?' },
      { en: 'Tome un comprimido tres veces al día con comida.', pt: 'Tome um comprimido três vezes ao dia com comida.' },
      { en: '¿Necesito receta para esto?', pt: 'Preciso de receita para isso?' },
      { en: '¿Hay alguna farmacia cerca?', pt: 'Tem alguma farmácia por perto?' },
      { en: 'Me gustaría pedir cita.', pt: 'Gostaria de marcar uma consulta.' },
    ],
    dialog: [
      { who: 'them', en: 'Hola, pase. ¿Qué le trae por aquí hoy?', pt: 'Olá, entre. O que te traz aqui hoje?' },
      { who: 'you', en: 'No me encuentro bien. Me duele la garganta y tengo dolor de cabeza.', pt: 'Não estou bem. Estou com garganta inflamada e dor de cabeça.' },
      { who: 'them', en: '¿Desde cuándo tiene estos síntomas?', pt: 'Há quanto tempo você está com esses sintomas?' },
      { who: 'you', en: 'Desde ayer por la mañana. También tengo un poco de fiebre.', pt: 'Desde ontem de manhã. Também estou com febre baixa.' },
      { who: 'them', en: '¿Tiene alguna alergia a medicamentos?', pt: 'Você tem alguma alergia a medicamentos?' },
      { who: 'you', en: 'Sí, soy alérgica a la penicilina.', pt: 'Sim, sou alérgica à penicilina.' },
      { who: 'them', en: 'De acuerdo. Le voy a recetar algo seguro. Tome un comprimido tres veces al día con comida.', pt: 'Ok. Vou te receitar algo seguro. Tome um comprimido três vezes ao dia com comida.' },
      { who: 'you', en: '¿Cuántos días tengo que tomarlo?', pt: 'Por quantos dias devo tomar?' },
      { who: 'them', en: 'Durante cinco días. Si no mejora en dos días, vuelva a verme.', pt: 'Por cinco dias. Se não melhorar em dois dias, volte aqui.' },
      { who: 'you', en: 'Gracias, doctor. ¿Hay alguna farmacia cerca?', pt: 'Obrigada, doutor. Tem alguma farmácia por perto?' },
    ],
  },
]

export const PHRASEBOOKS: Record<TargetLang, Scenario[]> = { en: EN, es: ES }
